### ISSUE TITLE
Wiki "Run it as a Service" missing

### ISSUE THREAD

**Issue by Rustimation** [philippoo66/optolink-splitter#36]
Hello Phil,
it seems that the wiki page "Run it as a service" (https://github.com/philippoo66/optolink-splitter/wiki/optolinkvs2_switch-automatisch-starten) has gone into the bit bucket, i.e. it's no longer available. Instead, I'm getting a "Create a new page" page. Maybe you can recreate that page. I know it was there previously. 
Kind regards 
Chris (rustimation.eu)

**Comment by Rustimation** [comment]
Ahh. Found it. The link on the readme page (https://github.com/philippoo66/optolink-splitter/) is broken....

**Comment by philippoo66** [comment]
oh, thank you, I will fix that

**Comment by philippoo66** [comment]
I fixed it ;-)
